// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOBK4zNbw-Pxur8oR18lzq19ttdUnxXwo',
    appId: '1:1069309175593:web:8a8c98e44d1dabf5d83938',
    messagingSenderId: '1069309175593',
    projectId: 'gomuluproject',
    authDomain: 'gomuluproject.firebaseapp.com',
    databaseURL: 'https://gomuluproject-default-rtdb.firebaseio.com',
    storageBucket: 'gomuluproject.appspot.com',
    measurementId: 'G-ZLZQXPHCDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ8GlRK88mX-1VI6mDwE1hXWCXu0RfEMU',
    appId: '1:1069309175593:android:89c306622884fb0dd83938',
    messagingSenderId: '1069309175593',
    projectId: 'gomuluproject',
    databaseURL: 'https://gomuluproject-default-rtdb.firebaseio.com',
    storageBucket: 'gomuluproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxvmCByWthwVlJnIt8Bap1f4t3eLEHm44',
    appId: '1:1069309175593:ios:995ab98edf910876d83938',
    messagingSenderId: '1069309175593',
    projectId: 'gomuluproject',
    databaseURL: 'https://gomuluproject-default-rtdb.firebaseio.com',
    storageBucket: 'gomuluproject.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxvmCByWthwVlJnIt8Bap1f4t3eLEHm44',
    appId: '1:1069309175593:ios:d74d260c9cdd5f07d83938',
    messagingSenderId: '1069309175593',
    projectId: 'gomuluproject',
    databaseURL: 'https://gomuluproject-default-rtdb.firebaseio.com',
    storageBucket: 'gomuluproject.appspot.com',
    iosBundleId: 'com.example.untitled1.RunnerTests',
  );
}
